# docker-compose
version: "3"
services:
  app:
    container_name: 'game-of-life-dev'
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    command: bash -c "npm start"
